-- # Micro-ops
local rain = rain

rain.cfg = rain.cfg or {}

rain.cfg.HiddenUIElements = {}
rain.cfg.HiddenUIElements["CHudAmmo"] 				= true
rain.cfg.HiddenUIElements["CHudBattery"] 			= true
rain.cfg.HiddenUIElements["CHudCrosshair"] 			= true
rain.cfg.HiddenUIElements["CHudDamageIndicator"] 	= true
rain.cfg.HiddenUIElements["CHudGeiger"] 			= true
rain.cfg.HiddenUIElements["CHudHealth"] 			= true
rain.cfg.HiddenUIElements["CHudSecondaryAmmo"] 		= true
rain.cfg.HiddenUIElements["CHudSquadStatus"] 		= true
rain.cfg.HiddenUIElements["CHudZoom"] 				= true
rain.cfg.HiddenUIElements["CHudChat"] 				= true


rain.cfg.modifiable = {} -- these will have a menu on the client where settings can be changed.
rain.cfg.modifiable.DrawSuitOverlay = true
rain.cfg.PlayerModels = {}

local availableModels = {
	["eco_neutralb3"] = true,
	["eco_old"] = true,
	["now_neutral_razgr_1"] = true,
	["stalker_exo_proto"] = true,
	["stalker_medic"] = true,
	["stalker_military_loner_1"] = true,
	["stalker_military_loner_2"] = true,
	["stalker_military_loner_3"] = true,
	["stalker_military_loner_4"] = true,
	["stalker_military_loner_5"] = true,
	["stalker_neutral_0"] = true,
	["stalker_neutral_1_gasmask"] = true,
	["stalker_neutral_1_mask"] = true,
	["stalker_neutral_2_halfmask"] = true,
	["stalker_neutral_2_halfmask_b"] = true,
	["stalker_neutral_2_mask_nohood"] = true,
	["stalker_neutral_3"] = true,
	["stalker_neutral_3_nohood"] = true,
	["stalker_neutral_4_light"] = true,
	["stalker_neutral_5"] = true,
	["stalker_neutral_8"] = true,
	["stalker_neutral_9"] = true,
	["stalker_neutral_9d"] = true,
	["stalker_neutral_10"] = true,
	["stalker_neutral_11"] = true,
	["stalker_neutral_12"] = true,
	["stalker_neutral_13"] = true,
	["stalker_neutral_13b"] = true,
	["stalker_neutral_14"] = true,
	["stalker_neutral_15"] = true,
	["stalker_neutral_16"] = true,
	["stalker_neutral_16d"] = true,
	["stalker_neutral_17"] = true,
	["stalker_neutral_18"] = true,
	["stalker_neutral_hunter"] = true,
	["stalker_neutral_pro"] = true,
	["stalker_neutral_unique"] = true,
	["stalker_neutral0a"] = true,
	["stalker_neutral0b"] = true,
	["stalker_neutral0c"] = true,
	["stalker_neutral0d"] = true,
	["stalker_neutral1a"] = true,
	["stalker_neutral1a_mask"] = true,
	["stalker_neutral1b"] = true,
	["stalker_neutral1b_mask"] = true,
	["stalker_neutral1c"] = true,
	["stalker_neutral1c_mask"] = true,
	["stalker_neutral1d"] = true,
	["stalker_neutral1d_mask"] = true,
	["stalker_neutral1e"] = true,
	["stalker_neutral1e_mask"] = true,
	["stalker_neutral1f"] = true,
	["stalker_neutral1f_mask"] = true,
	["stalker_neutral2a"] = true,
	["stalker_neutral2a_mask"] = true,
	["stalker_neutral2amask1"] = true,
	["stalker_neutral2amask2"] = true,
	["stalker_neutral2b"] = true,
	["stalker_neutral2b_mask"] = true,
	["stalker_neutral2bmask1"] = true,
	["stalker_neutral2bmask2"] = true,
	["stalker_neutral2c"] = true,
	["stalker_neutral2c_mask"] = true,
	["stalker_neutral2cmask1"] = true,
	["stalker_neutral2cmask2"] = true,
	["stalker_neutral2d"] = true,
	["stalker_neutral2d_mask"] = true,
	["stalker_neutral2dmask1"] = true,
	["stalker_neutral2dmask2"] = true,
	["stalker_neutrala2"] = true,
	["stalker_neutralb2"] = true,
	["stalker_neutralb3"] = true,
	["stalker_neutralc2"] = true,
	["stalker_neutrale2"] = true,
	["stalker_neutralf2"] = true,
	["stalker_neutralg2"] = true,
	["stalker_neutralh1"] = true,
	["stalker_neutrali1"] = true,
	["stalker_nutral_nauchnyi"] = true,
	["stalker_soldier_4"] = true,
	["stalker_soldierb2"] = true,
	["stalker_soldierb3"] = true,
	["stalker_soldierb4"] = true
}

for k = 1, #availableModels do
	local v = availableModels[k]
	table.insert(rain.cfg.PlayerModels, "models/cakez/rxstalker/stalker_neutral/"..v..".mdl")
	v = nil
end
availableModels = nil